// <auto-generated />
using System;
using CaronaAlvinegra.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaronaAlvinegra.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLider")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PassageiroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassageiroId");

                    b.HasIndex("VeiculoId", "PassageiroId")
                        .IsUnique();

                    b.ToTable("Alocacoes", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adversario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Passageiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresencaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("PresencaId");

                    b.HasIndex("RotaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Passageiros", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Presenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConfirmadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RotaEfetivaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("RotaEfetivaId");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique();

                    b.ToTable("Presencas", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalEmbarque")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rotas", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RotaPreferencialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RotaPreferencialId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Classificacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fechado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Alocacao", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Passageiro", "Passageiro")
                        .WithMany()
                        .HasForeignKey("PassageiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passageiro");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Passageiro", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Presenca", "Presenca")
                        .WithMany()
                        .HasForeignKey("PresencaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Presenca");

                    b.Navigation("Rota");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Presenca", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Rota", "RotaEfetiva")
                        .WithMany()
                        .HasForeignKey("RotaEfetivaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("RotaEfetiva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CaronaAlvinegra.Domain.Entities.Rota", "RotaPreferencial")
                        .WithMany()
                        .HasForeignKey("RotaPreferencialId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Grupo");

                    b.Navigation("RotaPreferencial");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("CaronaAlvinegra.Domain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("CaronaAlvinegra.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
